### ISSUE TITLE
Error running google web fonts (path.posix.join)

### ISSUE THREAD

**Issue by joeykamsteeg** [battlesnake/gulp-google-webfonts#26]
Running gulp-google-webfonts outputs the following error.
We are using the example code in README file. 

Maybe the following output message will help with fixing this issue.

```
/.././node_modules/gulp-google-webfonts/index.js:275
				request.name = path.posix.join(options.fontsDir, request.name);
				                          ^
TypeError: Cannot call method 'join' of undefined
    at makeFontFace (/.././node_modules/gulp-google-webfonts/index.js:275:31)
    at Array.map (native)
    at generateFontCss (/.././node_modules/node_modules/gulp-google-webfonts/index.js:265:6)
    at parseCss (/.././node_modules/gulp-google-webfonts/index.js:216:4)
    at fn (/.././node_modules/async/lib/async.js:638:34)
    at Object._onImmediate (/.././node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by battlesnake** [comment]
You're provably either using an ancient version of node, or you aren't using the built-in "path" module.  Ensure you are using a recent version of node and that you do not have "path" in your node_modules.
