### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:443 (Oswald font only)

### ISSUE THREAD

**Issue by danrwalker** [battlesnake/gulp-google-webfonts#45]
I am using the following font.list
```
# Google format
Oswald:400,700
Montserrat:300,400,600,800
Open+Sans:300,400,600,800
Lato:300,400
```

I get the following error:
```
Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
```

When removing "Oswald:400,700" from the list everything works as expected, fonts are downloaded and CSS is created. I have tried a couple of combinations of fonts, Oswald seems to be the only one not supported.

Heres the google link for the font: https://fonts.googleapis.com/css?family=Oswald:400,700&display=swap

**Comment by danrwalker** [comment]
Upon looking into this further I think that the issues might be that the Oswald font comes back as a non standard font weight:
```
@font-face {
  font-family: 'Oswald';
  font-style: normal;
  font-weight: 200 700;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/oswald/v23/TK3iWkUHHAIjg752FD8Gl-1PK62t.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
```

It would appear that the regX used (line 241 of index.js) to detect the font weight is not picking this up correctly.

Currently: `"\\s*font-weight:\\s*(\\w+);",`

Suggested: `\\s*font-weight:\\s*([\\w\\s]+);`

Also I have noticed that the are no local() parts in the returned font-face from google, would this also be a problem?

**Comment by samjameswatson** [comment]
I am also having this same issue but with the "Arvo" font - I tried to find a commonality between Arvo and Oswald but can't see any. Most fonts I tested worked fine but some returned ECONNREFUSED.

I also amended the regex as @danrwalker suggested but it didn't seem to make a difference for me - I believe Oswald is not returning font-weight 200 any longer.

**Comment by salim523** [comment]
I am also having the same problem with Oswald. I try all the options but non of them are working. Below is the error code.

```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:466:23)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)
```

**Comment by danrwalker** [comment]
The issue comes about when the font weight parameter contains more than one weight. This means that the font files provided for that particular font-face are to be used for more than one weight, there was also some issues when detecting fonts that didn't have local() options in the SRC which Oswald did not.

I was working on a fix that ended up finding more issues and I ran out of time on the project. I have listed my changes below if any help to anyone. I believe this issues is now being fixed in #47 although I am not sure if that fix has the multiple font weight part in it as mentioned in previous comment. 

Updated detection for both Local and Font Weight
```
var re = new RegExp([
	"\\s*font-family:\\s*'([^']+)';",
	"\\s*font-style:\\s*(\\w+);",
	"\\s*font-weight:\\s*([\\w\\s]+);",
	"\\s*src:\\s*(local\\('([^']+)'\\),\\s*local\\('([^']+)'\\),\\s*)?url\\(([^)]+)\\)[^;]*;",
	".*(?:unicode-range:([^;]+);)?",
].join(''), 'm');
```

Check see if local exists before outputting, added localBoth
```
function formatData(block, family, style, weight, localBoth, local1, local2, url, range) {
	var name = [family, style, weight].join('-') + '.' + ext;
	return {
		family: family,
		style: style,
		weight: weight,
		name: name.replace(/\s/g, '_'),
		url: url,
		local1: (!local1 || local1 === undefined) ? '' : local1,
		local2: (!local2 || local2 === undefined) ? '' : local2,
		range: range || 'U+0-10FFFF'
	};
}
```

Did a replace on the local part to correct an issue 
```
function makeFontFace(request) {
	request.uri = path.posix.join(
		options.relativePaths ? path.posix.relative(options.cssDir, options.fontsDir) : options.fontsDir,
		request.name
	);
	request.name = path.posix.join(options.fontsDir, request.name);
	return template
		.replace(/\$(\w+)/g, function (m, name) {
			return request[name];
		}).replace(/(local\(\'\'\)\,\s)/g,'');
}
```

I didn't commit my work as it was never fully tested/finished, hopefully you might find it helpful.

**Comment by malord** [comment]
v3.0.0 branch worked for me but I had to add it with:
